@startuml

title __DTO's Class Diagram__\n

  namespace nl.han.oose.jellema.rick.servicelayer {
    namespace dto {
      class nl.han.oose.jellema.rick.servicelayer.dto.PlaylistDTO {
          - id : int
          - name : String
          - owner : boolean
          - tracks : ArrayList<TrackDTO>
          - user : String
          + PlaylistDTO()
          + PlaylistDTO()
          + addToTrack()
          + getId()
          + getName()
          + getTracks()
          + getUser()
          + isOwner()
          + setId()
          + setName()
          + setOwner()
          + setTracks()
          + setUser()
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.servicelayer {
    namespace dto {
      class nl.han.oose.jellema.rick.servicelayer.dto.PlaylistsDTO {
          - length : int
          - playlists : ArrayList<PlaylistDTO>
          + PlaylistsDTO()
          + PlaylistsDTO()
          + addToLength()
          + addToPlaylist()
          + getLength()
          + getPlaylists()
          + setLength()
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.servicelayer {
    namespace dto {
      class nl.han.oose.jellema.rick.servicelayer.dto.TrackDTO {
          - album : String
          - description : String
          - duration : int
          - id : int
          - offlineAvailable : boolean
          - performer : String
          - playcount : int
          - publicationDate : Date
          - title : String
          + TrackDTO()
          + TrackDTO()
          + getAlbum()
          + getDescription()
          + getDuration()
          + getId()
          + getPerformer()
          + getPlaycount()
          + getPublicationDate()
          + getTitle()
          + isOfflineAvailable()
          + setAlbum()
          + setDescription()
          + setDuration()
          + setId()
          + setOfflineAvailable()
          + setPerformer()
          + setPlaycount()
          + setPublicationDate()
          + setTitle()
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.servicelayer {
    namespace dto {
      class nl.han.oose.jellema.rick.servicelayer.dto.TracksDTO {
          - tracks : ArrayList<TrackDTO>
          + TracksDTO()
          + TracksDTO()
          + addTrack()
          + getTracks()
          + setTracks()
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.servicelayer {
    namespace dto {
      class nl.han.oose.jellema.rick.servicelayer.dto.UserDTO {
          - password : String
          - token : String
          - user : String
          + UserDTO()
          + UserDTO()
          + getPassword()
          + getToken()
          + getUser()
          + setPassword()
          + setToken()
          + setUser()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
