@startuml

title __SPOTITUBE's Class Diagram__\n

  namespace nl.han.oose.jellema.rick.data.dao {
    class nl.han.oose.jellema.rick.data.dao.PlaylistsDao {
    }
  }
  

  namespace nl.han.oose.jellema.rick.data.dao {
    class nl.han.oose.jellema.rick.data.dao.TracksDao {
    }
  }
  

  namespace nl.han.oose.jellema.rick.data.dao {
    class nl.han.oose.jellema.rick.data.dao.UserDao {
    }
  }
  

  namespace nl.han.oose.jellema.rick.data.dao {
    namespace interfaces {
      interface nl.han.oose.jellema.rick.data.dao.interfaces.IPlaylistsDao {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.data.dao {
    namespace interfaces {
      interface nl.han.oose.jellema.rick.data.dao.interfaces.ITracksDao {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.data.dao {
    namespace interfaces {
      interface nl.han.oose.jellema.rick.data.dao.interfaces.IUserDao {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.data.database {
    class nl.han.oose.jellema.rick.data.database.Database {
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    class nl.han.oose.jellema.rick.resources.LoginResource {
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    class nl.han.oose.jellema.rick.resources.PlaylistResource {
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    class nl.han.oose.jellema.rick.resources.TrackResource {
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.AuthenticationExceptionMapper {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.DatabaseExceptionMapper {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.FileNotFoundExceptionMapper {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.InvalidTokenExceptionMapper {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.TrackDoesNotExistExceptionMapper {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    class nl.han.oose.jellema.rick.services.Cache {
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    class nl.han.oose.jellema.rick.services.LoginService {
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    class nl.han.oose.jellema.rick.services.PlaylistService {
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    class nl.han.oose.jellema.rick.services.TokenDealer {
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    class nl.han.oose.jellema.rick.services.TracksService {
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace dto {
      class nl.han.oose.jellema.rick.services.dto.PlaylistDTO {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace dto {
      class nl.han.oose.jellema.rick.services.dto.PlaylistsDTO {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace dto {
      class nl.han.oose.jellema.rick.services.dto.TrackDTO {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace dto {
      class nl.han.oose.jellema.rick.services.dto.TracksDTO {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace dto {
      class nl.han.oose.jellema.rick.services.dto.UserDTO {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace exceptions {
      class nl.han.oose.jellema.rick.services.exceptions.AuthenticationException {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace exceptions {
      class nl.han.oose.jellema.rick.services.exceptions.FileNotFoundException {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace exceptions {
      class nl.han.oose.jellema.rick.services.exceptions.InvalidTokenException {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace exceptions {
      class nl.han.oose.jellema.rick.services.exceptions.TrackDoesNotExistException {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace interfaces {
      interface nl.han.oose.jellema.rick.services.interfaces.ICache {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace interfaces {
      interface nl.han.oose.jellema.rick.services.interfaces.ILoginService {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace interfaces {
      interface nl.han.oose.jellema.rick.services.interfaces.IPlaylistService {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace interfaces {
      interface nl.han.oose.jellema.rick.services.interfaces.ITokenDealer {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace interfaces {
      interface nl.han.oose.jellema.rick.services.interfaces.ITracksService {
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.services {
    namespace utils {
      class nl.han.oose.jellema.rick.services.utils.PropertiesFiles {
      }
    }
  }
  

  nl.han.oose.jellema.rick.data.dao.PlaylistsDao .up.|> nl.han.oose.jellema.rick.data.dao.interfaces.IPlaylistsDao
  nl.han.oose.jellema.rick.data.dao.PlaylistsDao o-- nl.han.oose.jellema.rick.data.database.Database : database
  nl.han.oose.jellema.rick.data.dao.TracksDao .up.|> nl.han.oose.jellema.rick.data.dao.interfaces.ITracksDao
  nl.han.oose.jellema.rick.data.dao.TracksDao o-- nl.han.oose.jellema.rick.data.database.Database : database
  nl.han.oose.jellema.rick.data.dao.UserDao .up.|> nl.han.oose.jellema.rick.data.dao.interfaces.IUserDao
  nl.han.oose.jellema.rick.data.database.Database o-- nl.han.oose.jellema.rick.services.utils.PropertiesFiles : loadProperties
  nl.han.oose.jellema.rick.resources.LoginResource o-- nl.han.oose.jellema.rick.services.interfaces.ILoginService : loginService
  nl.han.oose.jellema.rick.resources.PlaylistResource o-- nl.han.oose.jellema.rick.services.interfaces.IPlaylistService : playListService
  nl.han.oose.jellema.rick.resources.TrackResource o-- nl.han.oose.jellema.rick.services.interfaces.ITracksService : tracksService
  nl.han.oose.jellema.rick.resources.mappers.AuthenticationExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  nl.han.oose.jellema.rick.resources.mappers.DatabaseExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  nl.han.oose.jellema.rick.resources.mappers.FileNotFoundExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  nl.han.oose.jellema.rick.resources.mappers.InvalidTokenExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  nl.han.oose.jellema.rick.resources.mappers.TrackDoesNotExistExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  nl.han.oose.jellema.rick.services.Cache .up.|> nl.han.oose.jellema.rick.services.interfaces.ICache
  nl.han.oose.jellema.rick.services.LoginService .up.|> nl.han.oose.jellema.rick.services.interfaces.ILoginService
  nl.han.oose.jellema.rick.services.LoginService o-- nl.han.oose.jellema.rick.services.interfaces.ICache : cache
  nl.han.oose.jellema.rick.services.LoginService o-- nl.han.oose.jellema.rick.services.interfaces.ITokenDealer : dealer
  nl.han.oose.jellema.rick.services.PlaylistService .up.|> nl.han.oose.jellema.rick.services.interfaces.IPlaylistService
  nl.han.oose.jellema.rick.services.PlaylistService o-- nl.han.oose.jellema.rick.services.interfaces.ICache : cache
  nl.han.oose.jellema.rick.services.PlaylistService o-- nl.han.oose.jellema.rick.data.dao.interfaces.IPlaylistsDao : playlistsDao
  nl.han.oose.jellema.rick.services.PlaylistService o-- nl.han.oose.jellema.rick.data.dao.interfaces.ITracksDao : tracksDao
  nl.han.oose.jellema.rick.services.TokenDealer .up.|> nl.han.oose.jellema.rick.services.interfaces.ITokenDealer
  nl.han.oose.jellema.rick.services.TracksService .up.|> nl.han.oose.jellema.rick.services.interfaces.ITracksService
  nl.han.oose.jellema.rick.services.TracksService o-- nl.han.oose.jellema.rick.services.interfaces.ICache : cache
  nl.han.oose.jellema.rick.services.TracksService o-- nl.han.oose.jellema.rick.data.dao.interfaces.ITracksDao : dao


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
