@startuml

title __MAPPERS's Class Diagram__\n

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.AuthenticationExceptionMapper {
          + toResponse()
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.DatabaseExceptionMapper {
          + toResponse()
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.FileNotFoundExceptionMapper {
          + toResponse()
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.InvalidTokenExceptionMapper {
          + toResponse()
      }
    }
  }
  

  namespace nl.han.oose.jellema.rick.resources {
    namespace mappers {
      class nl.han.oose.jellema.rick.resources.mappers.TrackDoesNotExistExceptionMapper {
          + toResponse()
      }
    }
  }
  

  nl.han.oose.jellema.rick.resources.mappers.AuthenticationExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  nl.han.oose.jellema.rick.resources.mappers.DatabaseExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  nl.han.oose.jellema.rick.resources.mappers.FileNotFoundExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  nl.han.oose.jellema.rick.resources.mappers.InvalidTokenExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper
  nl.han.oose.jellema.rick.resources.mappers.TrackDoesNotExistExceptionMapper .up.|> javax.ws.rs.ext.ExceptionMapper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
